export interface KnownPort {
  port: number;
  protocol: 'TCP' | 'UDP' | 'TCP/UDP';
  service: string;
  description: string;
}

export const KNOWN_PORTS: KnownPort[] = [
  // 核心知名系统端口 (System Ports: 1 - 1023)
  { port: 7, protocol: 'TCP/UDP', service: 'Echo', description: 'Echo 协议，用于网络测试与回显' },
  { port: 20, protocol: 'TCP', service: 'FTP Data', description: 'FTP 文件传输协议 (数据传输端口)' },
  { port: 21, protocol: 'TCP', service: 'FTP Control', description: 'FTP 文件传输协议 (控制指令端口)' },
  { port: 22, protocol: 'TCP', service: 'SSH / SFTP', description: 'SSH 安全外壳协议，用于远程登录与加密传输' },
  { port: 23, protocol: 'TCP', service: 'Telnet', description: 'Telnet 远程终端协议 (未加密明文传输)' },
  { port: 25, protocol: 'TCP', service: 'SMTP', description: '简单邮件传输协议，用于电子邮件发送' },
  { port: 53, protocol: 'TCP/UDP', service: 'DNS', description: '域名解析服务 (Domain Name System)' },
  { port: 67, protocol: 'UDP', service: 'DHCP Server', description: '动态主机配置协议服务端端口' },
  { port: 68, protocol: 'UDP', service: 'DHCP Client', description: '动态主机配置协议客户端端口' },
  { port: 69, protocol: 'UDP', service: 'TFTP', description: '简单文件传输协议 (Trivial FTP)' },
  { port: 80, protocol: 'TCP', service: 'HTTP', description: '超文本传输协议，万维网 (Web) 默认未加密服务端口' },
  { port: 88, protocol: 'TCP/UDP', service: 'Kerberos', description: 'Kerberos 身份验证系统服务端口' },
  { port: 110, protocol: 'TCP', service: 'POP3', description: '邮局协议第 3 版，用于电子邮件接收' },
  { port: 119, protocol: 'TCP', service: 'NNTP', description: '网络新闻传输协议' },
  { port: 123, protocol: 'UDP', service: 'NTP', description: '网络时间协议，用于服务器时间同步' },
  { port: 135, protocol: 'TCP', service: 'MS RPC', description: '微软远程过程调用服务 (RPC Endpoint Mapper)' },
  { port: 137, protocol: 'UDP', service: 'NetBIOS Name', description: 'NetBIOS 名称解析服务端口' },
  { port: 138, protocol: 'UDP', service: 'NetBIOS Datagram', description: 'NetBIOS 数据报服务端口' },
  { port: 139, protocol: 'TCP', service: 'NetBIOS Session', description: 'NetBIOS 会话服务 (Windows 局域网共享)' },
  { port: 143, protocol: 'TCP', service: 'IMAP', description: '互联网邮件访问协议 (收取与同步邮件)' },
  { port: 161, protocol: 'UDP', service: 'SNMP', description: '简单网络管理协议 (管理轮询服务)' },
  { port: 162, protocol: 'UDP', service: 'SNMP Trap', description: 'SNMP 陷阱通知/警报接收服务' },
  { port: 179, protocol: 'TCP', service: 'BGP', description: '边界网关协议 (Border Gateway Protocol)' },
  { port: 389, protocol: 'TCP/UDP', service: 'LDAP', description: '轻量目录访问协议，用于企业统一身份认证' },
  { port: 443, protocol: 'TCP', service: 'HTTPS', description: '加密超文本传输协议，安全 Web 服务端口' },
  { port: 445, protocol: 'TCP', service: 'SMB / CIFS', description: '微软局域网网络文件与打印机共享协议' },
  { port: 465, protocol: 'TCP', service: 'SMTPS', description: '基于 SSL/TLS 的加密 SMTP 邮件发送端口' },
  { port: 500, protocol: 'UDP', service: 'IPsec / IKE', description: 'Internet 密钥交换协议，用于 IPsec VPN 协商' },
  { port: 514, protocol: 'UDP', service: 'Syslog', description: '系统日志服务，用于日志集中收集传输' },
  { port: 515, protocol: 'TCP', service: 'LPD / LPR', description: '行式打印机守护进程协议' },
  { port: 520, protocol: 'UDP', service: 'RIP', description: '路由信息协议 (Routing Information Protocol)' },
  { port: 587, protocol: 'TCP', service: 'SMTP Submission', description: '邮件提交端口 (通常要求客户端身份认证与 TLS)' },
  { port: 636, protocol: 'TCP', service: 'LDAPS', description: '基于 SSL/TLS 加密的 LDAP 目录服务端口' },
  { port: 853, protocol: 'TCP', service: 'DNS over TLS (DoT)', description: '基于 TLS 加密的安全域名解析服务' },
  { port: 873, protocol: 'TCP', service: 'Rsync', description: 'Rsync 远程增量文件同步服务端口' },
  { port: 989, protocol: 'TCP', service: 'FTPS Data', description: '基于 SSL 加密的 FTPS 数据传输端口' },
  { port: 990, protocol: 'TCP', service: 'FTPS Control', description: '基于 SSL 加密的 FTPS 控制指令端口' },
  { port: 993, protocol: 'TCP', service: 'IMAPS', description: '基于 SSL/TLS 加密的 IMAP 邮件接收协议' },
  { port: 995, protocol: 'TCP', service: 'POP3S', description: '基于 SSL/TLS 加密的 POP3 邮件接收协议' },

  // 用户与注册端口 (User / Registered Ports: 1024 - 49151)
  { port: 1080, protocol: 'TCP', service: 'SOCKS Proxy', description: 'SOCKS4 / SOCKS5 通用网络代理协议端口' },
  { port: 1099, protocol: 'TCP', service: 'Java RMI', description: 'Java 远程方法调用 (RMI) 注册表端口' },
  { port: 1194, protocol: 'UDP/TCP', service: 'OpenVPN', description: 'OpenVPN 虚拟专用网络默认通信端口' },
  { port: 1234, protocol: 'TCP', service: 'VLC Stream', description: 'VLC 媒体播放器网络串流默认端口' },
  { port: 1433, protocol: 'TCP', service: 'MS SQL Server', description: 'Microsoft SQL Server 关系型数据库默认端口' },
  { port: 1434, protocol: 'UDP', service: 'MSSQL Monitor', description: 'MSSQL 数据库实例监视与解析服务端口' },
  { port: 1521, protocol: 'TCP', service: 'Oracle Database', description: 'Oracle 数据库 Listener 监听程序默认端口' },
  { port: 1618, protocol: 'TCP', service: 'Sybase DB', description: 'Sybase 数据库服务端口' },
  { port: 1701, protocol: 'UDP', service: 'L2TP', description: '第二层隧道协议 (Layer 2 Tunneling Protocol)' },
  { port: 1723, protocol: 'TCP', service: 'PPTP', description: '点对点隧道协议 (PPTP VPN)' },
  { port: 1883, protocol: 'TCP', service: 'MQTT', description: 'MQTT 物联网轻量级消息传输协议未加密端口' },
  { port: 1900, protocol: 'UDP', service: 'SSDP / UPnP', description: '简单服务发现协议，局域网设备自动发现' },
  { port: 2049, protocol: 'TCP/UDP', service: 'NFS', description: '网络文件系统 (Network File System) 共享端口' },
  { port: 2181, protocol: 'TCP', service: 'Apache ZooKeeper', description: 'ZooKeeper 分布式协调服务客户端通信端口' },
  { port: 2375, protocol: 'TCP', service: 'Docker API', description: 'Docker Engine 未加密 HTTP 远程管理 API 端口' },
  { port: 2376, protocol: 'TCP', service: 'Docker TLS API', description: 'Docker Engine 基于 TLS 加密的远程管理 API 端口' },
  { port: 2379, protocol: 'TCP', service: 'etcd Client', description: 'etcd 分布式键值数据库客户端 API 端口' },
  { port: 2380, protocol: 'TCP', service: 'etcd Peer', description: 'etcd 集群节点内部通信与数据同步端口' },
  { port: 24224, protocol: 'TCP/UDP', service: 'Fluentd', description: 'Fluentd 日志收集服务默认数据输入端口' },
  { port: 3000, protocol: 'TCP', service: 'Node.js / React / Grafana', description: 'Node.js/React 开发服务器与 Grafana 监控面板默认端口' },
  { port: 3128, protocol: 'TCP', service: 'Squid Proxy', description: 'Squid Web 缓存代理服务器默认通信端口' },
  { port: 3306, protocol: 'TCP', service: 'MySQL / MariaDB', description: 'MySQL 和 MariaDB 关系型数据库服务端默认端口' },
  { port: 3389, protocol: 'TCP/UDP', service: 'Windows RDP', description: '微软 Windows 远程桌面连接协议 (Remote Desktop Protocol)' },
  { port: 3690, protocol: 'TCP', service: 'SVN', description: 'Subversion (SVN) 版本控制系统默认通信端口' },
  { port: 4000, protocol: 'TCP', service: 'Hexo / Gatsby', description: 'Hexo、Gatsby 等前端静态博客开发预览端口' },
  { port: 4369, protocol: 'TCP', service: 'Erlang EPMD', description: 'Erlang 端口映射器守护进程 (RabbitMQ 依附服务)' },
  { port: 4567, protocol: 'TCP', service: 'Sinatra', description: 'Ruby Sinatra 微框架默认开发服务器端口' },
  { port: 4840, protocol: 'TCP', service: 'OPC UA', description: 'OPC Unified Architecture 工业自动化通信协议端口' },
  { port: 5000, protocol: 'TCP', service: 'Flask / ASP.NET', description: 'Python Flask 开发服务器与 ASP.NET 默认监听端口' },
  { port: 5001, protocol: 'TCP', service: 'IPFS / Synology', description: 'IPFS 星际文件系统 API / 群晖 NAS HTTPS 管理端口' },
  { port: 5060, protocol: 'TCP/UDP', service: 'SIP', description: '会话发起协议 (VoIP 网络电话通信端口)' },
  { port: 5061, protocol: 'TCP', service: 'SIPS', description: '基于 TLS 加密的 SIP 网络电话协议端口' },
  { port: 5432, protocol: 'TCP', service: 'PostgreSQL', description: 'PostgreSQL 关系型开源数据库默认端口' },
  { port: 5672, protocol: 'TCP', service: 'RabbitMQ AMQP', description: 'RabbitMQ 消息中间件高级消息队列协议 (AMQP) 端口' },
  { port: 5900, protocol: 'TCP', service: 'VNC', description: 'VNC 远程桌面图形化控制服务端口' },
  { port: 5938, protocol: 'TCP/UDP', service: 'TeamViewer', description: 'TeamViewer 远程协助软件默认通信端口' },
  { port: 5984, protocol: 'TCP', service: 'CouchDB', description: 'Apache CouchDB 文档数据库 RESTful API 端口' },
  { port: 6000, protocol: 'TCP', service: 'X11', description: 'X Window 操作系统窗口显示服务 0 号显示屏端口' },
  { port: 6379, protocol: 'TCP', service: 'Redis', description: 'Redis 开源内存 Key-Value 数据库默认通信端口' },
  { port: 6443, protocol: 'TCP', service: 'Kubernetes API', description: 'Kubernetes 集群控制面 API Server 默认监听端口' },
  { port: 6667, protocol: 'TCP', service: 'IRC', description: '互联网中继聊天协议 (Internet Relay Chat)' },
  { port: 7001, protocol: 'TCP', service: 'Oracle WebLogic', description: 'WebLogic 应用服务器 Console 管理控制台端口' },
  { port: 7002, protocol: 'TCP', service: 'WebLogic SSL', description: 'WebLogic 应用服务器 HTTPS 安全管理端口' },
  { port: 7077, protocol: 'TCP', service: 'Apache Spark', description: 'Spark 独立集群 Master 节点通信端口' },
  { port: 7474, protocol: 'TCP', service: 'Neo4j HTTP', description: 'Neo4j 图数据库 Web 管理界面与 HTTP API' },
  { port: 7687, protocol: 'TCP', service: 'Neo4j Bolt', description: 'Neo4j 数据库 Bolt 协议数据传输端口' },
  { port: 8000, protocol: 'TCP', service: 'Django / FastAPI', description: 'Python Django / FastAPI 常用开发测试服务器端口' },
  { port: 8008, protocol: 'TCP', service: 'Matrix Synapse', description: 'Matrix 去中心化通讯服务与备用 HTTP 端口' },
  { port: 8080, protocol: 'TCP', service: 'HTTP Proxy / Tomcat', description: '常用 Web 代理与 Apache Tomcat / Spring Boot 默认端口' },
  { port: 8081, protocol: 'TCP', service: 'React Native / Nexus', description: 'React Native Metro 打包器 / Sonatype Nexus 制品库端口' },
  { port: 8086, protocol: 'TCP', service: 'InfluxDB', description: 'InfluxDB 时序数据库 HTTP API 通信端口' },
  { port: 8088, protocol: 'TCP', service: 'Hadoop YARN', description: 'Hadoop YARN 资源管理器 Web 控制台端口' },
  { port: 8123, protocol: 'TCP', service: 'ClickHouse / Home Assistant', description: 'ClickHouse 列式数据库 HTTP 端口与智能家居控制端' },
  { port: 8200, protocol: 'TCP', service: 'HashiCorp Vault', description: 'Vault 密钥与机密管理系统 API 端口' },
  { port: 8300, protocol: 'TCP', service: 'Consul RPC', description: 'HashiCorp Consul 服务发现与配置中心 RPC 端口' },
  { port: 8443, protocol: 'TCP', service: 'HTTPS Alt', description: '备用 HTTPS 加密 Web 服务常用端口' },
  { port: 8500, protocol: 'TCP', service: 'Consul HTTP', description: 'HashiCorp Consul Web 控制台与 HTTP API 端口' },
  { port: 8888, protocol: 'TCP', service: 'Jupyter Notebook / 宝塔', description: 'Jupyter 交互面板与宝塔 Linux 面板初始登录端口' },
  { port: 9000, protocol: 'TCP', service: 'PHP-FPM / MinIO / Sonar', description: 'PHP-FPM 服务监听端 / MinIO 对象存储 / SonarQube' },
  { port: 9001, protocol: 'TCP', service: 'Supervisor / MinIO Console', description: 'Supervisor 进程管理控制台 / MinIO Web Console' },
  { port: 9090, protocol: 'TCP', service: 'Prometheus', description: 'Prometheus 开源监控采集与查询 Web 控制台' },
  { port: 9091, protocol: 'TCP', service: 'Pushgateway', description: 'Prometheus Pushgateway 指标推送网关端口' },
  { port: 9092, protocol: 'TCP', service: 'Apache Kafka', description: 'Kafka 分布式流处理消息队列服务 Broker 通信端口' },
  { port: 9100, protocol: 'TCP', service: 'Node Exporter', description: 'Prometheus 主机硬件指标 Node Exporter 导出器端口' },
  { port: 9200, protocol: 'TCP', service: 'Elasticsearch HTTP', description: 'Elasticsearch 分布式搜索引擎 RESTful HTTP API 端口' },
  { port: 9300, protocol: 'TCP', service: 'Elasticsearch TCP', description: 'Elasticsearch 内部节点之间集群通信与传输端口' },
  { port: 9411, protocol: 'TCP', service: 'Zipkin', description: 'Zipkin 分布式链路追踪系统默认数据收集端口' },
  { port: 9876, protocol: 'TCP', service: 'RocketMQ NameServer', description: 'RocketMQ 命名服务 NameServer 通信端口' },
  { port: 10000, protocol: 'TCP', service: 'Webmin', description: 'Webmin 基于 Web 的类 Unix 系统管理工具端口' },
  { port: 10911, protocol: 'TCP', service: 'RocketMQ Broker', description: 'RocketMQ 消息服务器 Broker 默认通信端口' },
  { port: 11211, protocol: 'TCP/UDP', service: 'Memcached', description: 'Memcached 高性能分布式内存缓存服务端口' },
  { port: 15672, protocol: 'TCP', service: 'RabbitMQ Management', description: 'RabbitMQ Web 可视化管理控制台默认端口' },
  { port: 18830, protocol: 'TCP', service: 'MQTT SSL', description: '基于 TLS/SSL 加密的 MQTT 物联网通信端口' },
  { port: 19000, protocol: 'TCP', service: 'Envoy Admin', description: 'Envoy 高性能云原生代理 admin 管理接口端口' },
  { port: 27017, protocol: 'TCP', service: 'MongoDB', description: 'MongoDB NoSQL 文档数据库默认监听端口' },
  { port: 27018, protocol: 'TCP', service: 'MongoDB Shard', description: 'MongoDB 分片服务 (Shard) 默认监听端口' },
  { port: 27019, protocol: 'TCP', service: 'MongoDB Config', description: 'MongoDB 配置服务器 (Config Server) 端口' },
  { port: 28015, protocol: 'TCP', service: 'RethinkDB Driver', description: 'RethinkDB 客户端驱动通信端口' },

  // 动态 / 私有保留已知端口 (49152 - 65535)
  { port: 50000, protocol: 'TCP', service: 'Jenkins Agent / DB2', description: 'Jenkins 主从节点通信端口与 IBM DB2 默认端口' },
  { port: 50070, protocol: 'TCP', service: 'Hadoop NameNode', description: 'Hadoop HDFS NameNode Web 可视化 UI 端口' },
  { port: 51820, protocol: 'UDP', service: 'WireGuard VPN', description: 'WireGuard 现代极简安全 VPN 默认通信端口' },
  { port: 60000, protocol: 'UDP', service: 'Mosh Terminal', description: 'Mosh 移动 Shell 增强型远程终端默认端口' }
];

// 已知端口 Hash Set 用于 O(1) 过滤
export const KNOWN_PORTS_SET: Set<number> = new Set(KNOWN_PORTS.map(p => p.port));

// 为 K8s NodePort 范围 30000 - 32767 特殊补充标记校验（若需要也可纳入 knownCheck）
export const isKnownPort = (port: number): boolean => {
  if (KNOWN_PORTS_SET.has(port)) return true;
  return false;
};
